#!/bin/bash
# A simple command for re-loading
# Date： 2016/07/16 
# Created by NickLin

#cp -r kvm/ ../linux-4.4/arch/x86/
#cd ../linux-4.4/arch/x86/kvm/
#sudo make M=$PWD -C /lib/modules/`uname -r`/build

sudo rmmod kvm_intel kvm
sudo insmod ../linux-4.4/arch/x86/kvm/kvm.ko
sudo insmod ../linux-4.4/arch/x86/kvm/kvm-intel.ko enable_apicv=N

exit 0
